# Generated by Django 4.2.14 on 2025-07-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='message_type',
            field=models.CharField(choices=[('enquiry', 'General Enquiry'), ('bulk', 'Bulk Order Enquiry'), ('problem', 'Report a Problem'), ('other', 'Other')], default='enquiry', max_length=20),
        ),
    ]
