# Generated by Django 3.2.25 on 2025-07-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_alter_enquiry_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='order_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
