# Generated by Django 3.2.25 on 2025-06-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250622_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price_modifier', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price_modifier', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
            ],
            options={
                'verbose_name_plural': 'Wax Types',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='available_scents',
            field=models.ManyToManyField(blank=True, related_name='products_available_scents', to='products.Scent'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, related_name='products_available_sizes', to='products.CandleSize'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_wax_types',
            field=models.ManyToManyField(related_name='products_available_wax_types', to='products.WaxType'),
        ),
    ]
